name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  # ETAPA 1: Compilación de React Native Web
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node.js 24 va al inicio, antes de instalar dependencias
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: |
          cd frontend/mi-app
          npm install

      - name: Build Web App
        run: |
          cd frontend/mi-app
          npx expo export -p web

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/mi-app/dist

  # ETAPA 2: Publicación en el servidor de GitHub
  deploy-site:
    needs: deploy
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4